In [2]:
import pandas as pd

dummy = pd.read_csv("NSDUH_2020_Tab.txt", sep='\t')

/var/folders/gp/xs_xkf814zx898m2wdld0hw40000gn/T/ipykernel_12381/1612466860.py:3: DtypeWarning: Columns (2726) have mixed types. Specify dtype option on import or set low_memory=False.
  dummy = pd.read_csv("NSDUH_2020_Tab.txt", sep='\t')

In [11]:
dummy.head(10)

,QUESTID2,FILEDATE,CIGEVER,CIGOFRSM,CIGWILYR,CIGTRY,CIGYFU,CIGMFU,CIGREC,CIG30USE,...,GOVTPROG,INCOME,POVERTY3,PDEN10,COUTYP4,MAIIN102,AIIND102,ANALWTQ1Q4_C,VESTRQ1Q4_C,VEREP
0,10000182,10/25/2021,1,99,99,16,9999,99,1,30,...,2,4,3.0,3,3,2,2,16186.579071,40048,2
1,10001831,10/25/2021,1,99,99,8,9999,99,1,24,...,2,3,3.0,2,2,2,2,16809.072854,40022,2
2,10002722,10/25/2021,2,99,99,991,9991,91,91,91,...,2,2,3.0,1,1,2,2,1379.866862,40011,1
3,10002897,10/25/2021,2,99,99,991,9991,91,91,91,...,2,4,3.0,1,1,2,2,422.776340,40007,1
4,10004677,10/25/2021,2,4,4,991,9991,91,91,91,...,2,4,3.0,2,2,2,2,609.829709,40031,1
5,10004796,10/25/2021,2,99,99,991,9991,91,91,91,...,2,2,3.0,2,2,2,2,2529.748991,40041,2
6,10005265,10/25/2021,1,99,99,15,9999,99,1,15,...,2,4,3.0,1,1,2,2,11553.464620,40007,2
7,10005369,10/25/2021,2,99,99,991,9991,91,91,91,...,2,4,3.0,1,1,2,2,8611.643813,40008,1
8,10007045,10/25/2021,2,99,99,991,9991,91,91,91,...,2,4,3.0,1,1,2,2,1702.289471,40026,1
9,10007700,10/25/2021,1,99,99,16,9999,99,1,30,...,2,3,3.0,2,1,2,2,36135.050260,40002,2

In [9]:
marijuana_df = dummy[["MJEVER", "MJAGE", "MJYFU", "MJMFU", "MJREC", "MJYRTOT", "MRTOTFG", "MJFQFLG","MRBSTWAY", "MRDAYPYR", "MRDAYPMO","MRDAYPWK", "MJDAY30A", "MR30EST"]]

In [10]:
marijuana_df.to_csv("marijuana2020.csv")